### ISSUE TITLE
Failing to start on Mac due to in-use port fails to return 

### ISSUE THREAD

**Issue by drekka** [hummingbird-project/hummingbird#132]
Not sure if I'm right about this. I have a Mac command line target that's starting a Hummingbird server.

What appears to be happening is that if the port I ask it to start on is already taken, Hummingbird fail and hangs at this point:

<img width="1423" alt="Screen Shot 2022-07-20 at 10 35 03 pm" src="https://user-images.githubusercontent.com/153837/179983313-35deeb81-37c6-4eea-82d3-2358d9cb5999.png">

This doesn't seem to occur when running the same startup code on an iOS simulator, just when running via a Mac command.

Any clues how I might resolve this?

**Comment by bubudrc** [comment]
you can kill your localhost by running:

`$ lsof -n -i4TCP:8080`

PID is the second field. Then, kill that process:

`$ kill -9 PID`

[Here are more examples for different ports](https://stackoverflow.com/questions/24387451/how-can-i-kill-whatever-process-is-using-port-8080-so-that-i-can-vagrant-up)

**Comment by drekka** [comment]
That's not really an option. Firstly because I don't know what's already got the port and I might need it. Second because I need to start Hummingbird from Swift. So shell scripting it's a possibility at this point.

**Comment by adam-fowler** [comment]
If another process has the port, you can't bind to it, so you can't start your server. What do you expect Hummingbird to do at that point?

**Comment by drekka** [comment]
I expect it to stop with an error. It does that on iOS. On OS X it simply hangs. No error, nothing.

**Comment by adam-fowler** [comment]
I do remember seeing something recently about using RunLoop I'll need to do some more investigation

**Comment by drekka** [comment]
Yeah. That's what I did in https://github.com/hummingbird-project/hummingbird/pull/133 but the code I have there is probably pretty tacky as it was the first thing I could think of. Did solve the issue though :-)

**Comment by adam-fowler** [comment]
#135 should fix this

**Comment by adam-fowler** [comment]
This is now merged into main. Can you verify this works for you

**Comment by drekka** [comment]
Cool. Will get back to you.

**Comment by drekka** [comment]
Hi, I've run Hummingbird on both OSX and Linux using the `main` branch and it's worked exactly as expected. Thank you. I look forwards to having it in a release.

**Comment by adam-fowler** [comment]
Cheers, I should hopefully get a release out this morning
