### ISSUE TITLE
0.16.2, compilation error - HBLogRequestsMiddleware 32: Argument HBURL does not conform to expected type 'Sendable'

### ISSUE THREAD

**Issue by drekka** [hummingbird-project/hummingbird#136]
Hi, I just updated to 0.16.2 and I'm getting a compilation error on lines 32 & 38 of `HBLogRequestsMiddleware` where it's attempting to log `request.uri`:

```
if self.includeHeaders {
    request.logger.log(
        level: self.logLevel,
        "\(request.headers)",
        metadata: ["hb_uri": .stringConvertible(request.uri), "hb_method": .string(request.method.rawValue)] <-- Error!
    )
} else {
    request.logger.log(
        level: self.logLevel,
        "",
        metadata: ["hb_uri": .stringConvertible(request.uri), "hb_method": .string(request.method.rawValue)] <-- Error!
    )
}
```

Not sure why this is coming up now as it hasn't changed for some time and neither has the code in `.stringConvertable(...)`.

**Comment by drekka** [comment]
Ahh, I get it, it's part of the SwiftLog 1.4.3 update.

**Comment by drekka** [comment]
I've patched around this by anchoring SwiftLog at 1.4.2 in my package files so that it's not demanding `Sendable` conformance.

**Comment by drekka** [comment]
I've now raised a bug on SwiftLog: https://github.com/apple/swift-log/issues/228 From the lengthy discussion over there about adding `Sendable` is appears they thought it would just trigger a warning. So I'm wondering if perhaps there is something else at play here.

**Comment by ktoso** [comment]
let's discuss over in https://github.com/apple/swift-log/issues/228

**Comment by adam-fowler** [comment]
@drekka I have a fix on `main` for this, if you want to test

**Comment by drekka** [comment]
Cool thanks @adam-fowler. I'll give it a try. Looks like the Apple guys will be patching as well but I presume you would want to be adding `Sendable` anyway.

**Comment by drekka** [comment]
All fixed, both by you and by the Apple team. Thanks
