### ISSUE TITLE
HBParameters doesn't handle repeating query parameters.

### ISSUE THREAD

**Issue by drekka** [hummingbird-project/hummingbird#138]
Just came across some API calls here with repeating query parameters. Things like `...?category=cars&category=engines` (a bit contrived but still possible). I looked in the code for `HBParameters` and it's coded like I would have done it in that it's baed on a dictionary. But with this new information it needs to be able to handle repeating keys with different values. So I'm thinking more like an array of tuples or some simple struct type.

**Comment by adam-fowler** [comment]
Another common way to store these is to store an array of strings in place of a single string. I think I'll do that instead. So it would be a `[String: [String]]` instead of a `[String]`

**Comment by drekka** [comment]
Sounds good. Would it create any issue for retrieving values though since the result could be a single `String` or a `[String]`.

**Comment by adam-fowler** [comment]
I would probably include a separate API for accessing multiple parameters. The current api would just return the string or the first element of the array depending on what is stored.

**Comment by adam-fowler** [comment]
You wanna check out #139
