### ISSUE TITLE
`HBRequest.endpointPath` not set while applying middleware

### ISSUE THREAD

**Issue by slashmo** [hummingbird-project/hummingbird#155]
Within the context of middleware, the request's `endpointPath` property will always be `nil`. This is due to the `endpointPath` being set by the `TrieRouter` **after** all middleware was applied, as shown in the following call tree:

<img width="260" alt="image" src="https://user-images.githubusercontent.com/16192401/208730469-7d6de49d-538a-481d-be0f-087424c404b2.png">

In this call tree "0" refers to the following line:

https://github.com/hummingbird-project/hummingbird/blob/434fdd8d96e1ac2661c1150aefa95e127f2d942f/Sources/Hummingbird/Router/TrieRouter.swift#L53

I also checked the built-in `HBMetricsMiddleware` and it resulted in the same lack of an `endpointPath` while it was being applied. For Distributed Tracing support however the endpoint path is more or less required since it should be used as the span name.

**Comment by adam-fowler** [comment]
The metrics middleware should work as the metrics are set after the nextResponder (which will have called the TrieRouter) has completed. It was working, maybe I broke it when HBRequest was changed from a class to a struct. I thought I had tests for this.

**Comment by adam-fowler** [comment]
I have verified the `HBMetricsMiddleware` works ok. There is even a test to verify it works `MetricsTests.testParameterEndpoint`. 

As you have pointed out the router doesn't run before the middleware next responder has been called. But it has run after that point. So the endpointPath is available for metrics. Are you needing the endpoint path before the request is run? To setup a span do you need to know its name at initialisation? 

Changing it so the router runs before all the middleware is quite a large structural change. Although you could use a `HBRouterGroup`. For router groups to work you need to run the router before any middleware attached to the group can run. In the example below `MyMiddleware` will have `endpointPath` set straight off
```swift
app.router.group()
    .add(middleware: MyMiddleware())
    .get("test") { _ in return "test" }
```

**Comment by slashmo** [comment]
> I have verified the `HBMetricsMiddleware` works ok. There is even a test to verify it works `MetricsTests.testParameterEndpoint`.

Hm, that's surprising to me. Yesterday when I set up the metrics middleware as a global middleware on the application it resulted in almost the same call tree as with my new tracing middleware (which I configured the same way). How do you set it up to have it be called afterwards without using a router group?

**Comment by slashmo** [comment]
> Are you needing the endpoint path before the request is run? To setup a span do you need to know its name at initialization?

It would be good to have it so that the route path can be taken into account when making a sampling decision.

**Comment by adam-fowler** [comment]
> How do you set it up to have it be called afterwards without using a router group?

A middleware can process both requests going out and when responses come back. eg
```swift
struct ExampleMiddleware: HBMiddleware {
    func apply(to request: HBRequest, next: HBResponder) -> EventLoopFuture<HBResponse> {
        processBefore(request)
        return next.respond(to: request).map { response in
            let response = processAfter(request, response)
            return response
        }
    }
}
```
The metrics middleware runs after the request has been processed. 
https://github.com/hummingbird-project/hummingbird/blob/434fdd8d96e1ac2661c1150aefa95e127f2d942f/Sources/Hummingbird/Middleware/MetricsMiddleware.swift#L28-L30

**Comment by slashmo** [comment]
> The metrics middleware runs after the request has been processed.

Ah, that makes sense. When I checked whether it's set in the metrics middleware I only checked the `processBefore` part of the `apply` method where it has not been set.

For Tracing it'd be nice to have it there, but as a workaround we could also keep track of the request's start time and then start the span after the response was returned, passing in the stored start time manually as the start time of the span.

**Comment by adam-fowler** [comment]
Are you looking to add a tracing middleware to HB by any chance?

**Comment by slashmo** [comment]
> Are you looking to add a tracing middleware to HB by any chance?

Yes, I'm currently working on a demo project for [swift-otel](https://github.com/slashmo/swift-otel) where I'm using Hummingbird as the web framework for a couple of services. Eventually I'd like to upstream the tracing support to Hummingbird.

**Comment by adam-fowler** [comment]
I'd be very happy to include a tracing middleware in HB.

**Comment by slashmo** [comment]
Cool! I'll push my draft implementation as soon as I worked around the endpoint path issue.

**Comment by slashmo** [comment]
I think we can close this issue in the meantime because as you pointed out it would require a larger refactoring to have the router called before all middleware. Tracing shouldn't be the (only) reason for that refactoring.
