### ISSUE TITLE
ByteBufferAllocator is not available through HBApplication

### ISSUE THREAD

**Issue by tib** [hummingbird-project/hummingbird#159]
Currently there's no way to access the channel's `ByteBufferAllocator` through the application instance.

It'd be really nice to have a property on `HBAppication`, to return the shared allocator. 

Thanks,
Tib.

**Comment by adam-fowler** [comment]
Looking at the code you can access it via `HBApplication.server.channel?.allocator`. The allocator is only setup once the server is running.

**Comment by tib** [comment]
Oh, thanks, I was not aware of this, but would be so nice to get a shorthand, this way we could simply reach the shared allocator just like the `eventLoopGroup` property, in other words: `app.allocator`. 

(maybe introduce an application context, just like the request context to get back the ELG, EL & allocator?)

```swift
HBApplicationContext {

var eventLoop: EventLoop
    /// returns the elg
    var eventLoopGroup: EventLoopGroup 

    /// returns the next event loop using the group?
    var eventLoop: EventLoop
 
    /// returns the shared allocator (or creates a new one if the server is not running)?
    var allocator: ByteBufferAllocator 
}

app.context: HBApplicationContext
```

I'm just sharing some ideas... but what do you think? 🤔

**Comment by adam-fowler** [comment]
Providing a shorthand for the byte buffer allocator would be possible but it would have to return an optional value which is not ideal. 

The request context is there to support multiple sources of requests. It is needed by hummingbird-lambda. So I don't think an application context makes sense here.

**Comment by adam-fowler** [comment]
@tib I don't think this makes sense in the end. The allocator is only available once running code from a `Channel`. The application code can be run from anywhere
