### ISSUE TITLE
Endpoint path incorrect for router group index routes

### ISSUE THREAD

**Issue by slashmo** [hummingbird-project/hummingbird#166]
When using a router group in combination with index routes, the endpoint path for those requests incorrectly (IMO) has a trailing slash:

```swift
let group = router.group("/users")
group.get(use: list)

func list(request: HBRequest) {
  // here I'd expect request.endpointPath to be "/users", but it is "/users/"
}
```

This might be a regression from https://github.com/hummingbird-project/hummingbird/pull/164.

**Comment by adam-fowler** [comment]
So should `group.get("/", use: list)` have a trailing slash, even though the router would treat them as the same route.

**Comment by slashmo** [comment]
Good point 🤔 My reasoning for expecting `/users` is that if I wouldn't use a router group, I'd write `router.get("/users")`, not `router.get("/users/")`, resulting in `/users` and not `/users/`.

In the case you shared I'd probably still expect `/users`, but that's even more opinionated I suppose.

If we say `group.get("/", use: list)` shouldn't have the trailing slash it should be consistent though and all trailing slashes in routes should be stripped, except for the case of the root index route which shouldn't be empty.

**Comment by adam-fowler** [comment]
#167 consistency is a good thing
