### ISSUE TITLE
URLEncodedForm: Parse array indices

### ISSUE THREAD

**Issue by adam-fowler** [hummingbird-project/hummingbird#17]
Currently arrays are formatted as follows
```
value[]=1&value[]=2
```
Add possibility of parsing arrays in form
```
value[0]=1&value[1]=2
```

**Comment by supersonicbyte** [comment]
Hey! Is this still something that needs to be implemented?

**Comment by adam-fowler** [comment]
> Hey! Is this still something that needs to be implemented?

I wrote this issue three years ago, I can't remember offhand what the context was. There certainly hasn't been any work on it since then.

The standard for arrays in url encoded form data, doesn't seem very clear but both of the above are valid. So we should probably support both. If you want to implement the parsing for the second format that'd be great

**Comment by supersonicbyte** [comment]
Sure, I would love to try to implement the parsing.
