### ISSUE TITLE
Feature: Associate a unique ID with each request

### ISSUE THREAD

**Issue by Joannis** [hummingbird-project/hummingbird#172]
Vapor keeps a unique ID for each request which, although not publicly exposed yet, allows us to track logs related to a specific request. I think that this kind of information could also be useful for logs originating from a handled Hummingbird Request.

Related: https://github.com/vapor/vapor/pull/2964

**Comment by adam-fowler** [comment]
The logger attached to HBRequest already has a unique id. Do you see any other reason for attaching a unique id to the request?

**Comment by Joannis** [comment]
As far as I can tell at least, there's no access to this unique ID. I think that it would be helpful to know this ID so that it can be set on loggers in third-party libraries such as MongoKitten.

**Comment by Joannis** [comment]
By 'no access' I mean no guaranteed stable API, you can of course subscript the logger with the same constant defined in HB or Vapor. But that's not quite the same level of reliability as being able to get `request.id`

**Comment by adam-fowler** [comment]
Something like
```swift
public var id: String { self.logger[metadataKey: "hb_id"]!.description }
```

**Comment by Joannis** [comment]
That would work for me
