### ISSUE TITLE
Catch anything as a path component 

### ISSUE THREAD

**Issue by tib** [hummingbird-project/hummingbird#176]
Seems like the wildcard support works quite different as I was expecting.

e.g.

```swift
router.get("*") { req in
    return req.uri.description
}
```
GET /foo => ok 
GET /foo/bar => 404

or 

```swift
router.get("*/*/*") { req in
    return req.uri.description
}
```

GET /foo/bar/baz => ok
GET /foo/bar     => 404

This behavior is just fine, but is there a way to catch more path components using a dynamic approach? This could be useful for frontend frameworks, for dynamic routes & SEO support this is a must have feature.

In Vapor we have `**` for this purpose. [See this link](https://docs.vapor.codes/basics/routing/#catchall).

Currently if I don't set parameters for a given route, the app Crashes with the following error:

```
Hummingbird/Extensions.swift:111: Fatal error: Cannot access HBRequest.parameters on a route not extracting parameters from the URI.
2023-03-17 14:38:23.077213+0100 Server[15185:10028744] Hummingbird/Extensions.swift:111: Fatal error: Cannot access HBRequest.parameters on a route not extracting parameters from the URI.
```

What if we change this behavior and always return the parameters as an array of strings, separated by a / character? This could also allow a catch all pattern somehow...

I'm just throwing in some ideas, but catching path components could be really useful. 
If somethings similar already exists in the project, please let me know. Thank you.

**Comment by adam-fowler** [comment]
- Yeah we don't have catch all `**` support yet. It's on the list. I'll add a separate issue to cover that. 
- Regarding accessing the parameters I think we can change it to be slightly less aggressive than a crash, maybe just return an empty parameter list.

**Comment by adam-fowler** [comment]
Question does `**` also mean nothing
eg 
```swift
router.get("/test/**") { req in
    return req.uri.description
}
```
work for 
GET /test/

**Comment by adam-fowler** [comment]
I will look at a catch all, but I want to look at setting up with package-benchmarks first as router changes can have performance implications.
