### ISSUE TITLE
Make a suggestion.

### ISSUE THREAD

**Issue by Muning69** [hummingbird-project/hummingbird#186]
You can change the type names in the library to a uniform naming method, such as removing the HB prefix from names such as HBApplication, HBRequestEncode, and so on. Because the library is open to all developers, developers can define their own names based on their needs. This is more conducive to the development of the library and also makes the semantics more explicit.

**Comment by adam-fowler** [comment]
Sorry are you saying you don't like the `HB` prefix? It is there because many of the types have quite generic names (request, response, application...) and I would rather not create symbol clashes with other libraries.

**Comment by Muning69** [comment]
Each library has its own unique prefix, which is not easy to conflict with other library names. However, because it is an open library, it needs to face the vast majority of developers. Removing the prefix can make it more semantically explicit, and it will also be faster and easier to understand for learning it. It will also make it more promising and more official. As for the possibility of name conflicts, developers can rename them themselves. For example, Swift has a typealias that can be used to retrieve aliases.
My English expression is not good, and it may be difficult for you to understand. Sorry.

**Comment by Muning69** [comment]
The relevant type names of the Vapor library are very good. Although some people say that it is not standard to prefix them, I mostly give you some suggestions from a semantic and intuitive perspective. Now that this library is just beginning to develop, if you consider this suggestion, removing the prefix now will be faster than removing it in the future, and I believe it will definitely develop better and better.

**Comment by adam-fowler** [comment]
> The relevant type names of the Vapor library are very good

I disagree with you here. They are aggressively acquiring symbol space with generic names. That is one of the reasons I included the `HB` prefix. I think we are going to have to agree to disagree

**Comment by tib** [comment]
100% agreed with this. The `HB` prefix is just fine, I like the fact that Hummingbird is not polluting the symbol space with generic names.
