### ISSUE TITLE
Serve static files

### ISSUE THREAD

**Issue by pepicrft** [hummingbird-project/hummingbird#199]
👋🏼 Hi!

I started using Hummingbird for a project, and I noticed the documentation nor the examples contain any reference about how to serve static files. Is there a building block for doing it or should I come up with my now implementation that reads the files using IO operations?

Thanks in advance.

**Comment by adam-fowler** [comment]
HummingbirdFoundation has `HBFileMiddleware`. Maybe I need to highlight it a bit better in the documentation

**Comment by pepicrft** [comment]
Thanks @adam-fowler 🙏🏼. That's what I was looking for

**Comment by pepicrft** [comment]
Indeed, I tried to use it to serve an SVG, and the server responds with a 304. Am I missing anything?

<img width="841" alt="image" src="https://github.com/hummingbird-project/hummingbird/assets/663605/6f7cd516-d79a-43c1-8dda-8ef61adb45ed">
<img width="645" alt="image" src="https://github.com/hummingbird-project/hummingbird/assets/663605/a027519e-34d2-4602-a23c-e29db299f80b">

Thanks

**Comment by adam-fowler** [comment]
What headers are you passing in with the request? If you are passing a `if-none-match` or `if-modified-since` header you could possibly get a 304 back.

**Comment by pepicrft** [comment]
Sure! These are the headers that the browser sent when trying to resolve an `<img/>` pointing to that SVG:

```
GET /images/logo.svg HTTP/1.1
Accept: image/webp,image/avif,video/*;q=0.8,image/png,image/svg+xml,image/*;q=0.8,*/*;q=0.5
Accept-Encoding: gzip, deflate
Accept-Language: en-GB,en;q=0.9
Connection: keep-alive
Host: 127.0.0.1:8080
Referer: http://127.0.0.1:8080/session
Sec-Fetch-Dest: image
Sec-Fetch-Mode: no-cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5.1 Safari/605.1.15
```

And here's the middleware setup:

```swift
let fileMiddleware = HBFileMiddleware("Public", cacheControl: HBCacheControl([(.imageSvg, [.maxAge(604800)])]), application: app)
app.middleware.add(fileMiddleware)
```

**Comment by adam-fowler** [comment]
You only get a 304 back if the asset is cached by your browser and the eTag for the asset hasn't changed.
Have you tried clearing your cache.

I've verified this works as expected with Safari, Firefox and Chrome

**Comment by pepicrft** [comment]
> Have you tried clearing your cache?

That solved the issue :). Thanks for pointing it out.
