### ISSUE TITLE
2.x: HBFileIO without Foundation

### ISSUE THREAD

**Issue by Joannis** [hummingbird-project/hummingbird#201]
Is there a possibility we can get HBFileIO without Foundation in the future? I dug around, and I don't see why it's in the Foundation module.

https://github.com/hummingbird-project/hummingbird/blob/aa84090b472b2900003cce81208c419433c898fb/Sources/HummingbirdFoundation/Files/FileIO.swift#L22

**Comment by adam-fowler** [comment]
Makes sense. It was originally in HummingbirdFoundation simply because it was built to serve the file middleware which does require Foundation.
