### ISSUE TITLE
2.x: Split HBApplication into Builder and Running types

### ISSUE THREAD

**Issue by adam-fowler** [hummingbird-project/hummingbird#205]
Split `HBApplication` into `HBApplicationBuilder` which will be used to build the application and `HBApplication` which will be the immutable instance of the running application. This allows us to pass the application around as part of the request handler context without Sendable concerns.

This does cause some issues with application extensions, in that you would have to duplicate them across both the builder and running application types. But I might get around that by removing the extension framework. And push for people to use direct dependency injection, instead of hanging everything off the application

**Comment by MartinLau7** [comment]
I approve of using dependency injection solutions, ASP.net is also a proponent of dependency injection.

**Comment by adam-fowler** [comment]
#224
