### ISSUE TITLE
Support Swift Service Lifecycle v2.0.0

### ISSUE THREAD

**Issue by tannerdsilva** [hummingbird-project/hummingbird#233]
Hello,

Currently, hummingbird is using `swift-service-lifecycle` on tag `1.0.0-alpha9`.

As we know, this project never tagged a final release for `1.x.x`.

Recently, however, the first "wide release" was tagged at `2.0.0`.

Unfortunately, new Swift projects trying to target this `2.0.0` version of `swift-service-lifecycle` are currently unable to build with `hummingbird` as a dependency, since it was built on a preproduction version.

**Comment by adam-fowler** [comment]
To support swift service lifecycle v2 requires a major update for Hummingbird as well. We are currently looking at a v2 HB in the branch `2.x.x`.

**Comment by adam-fowler** [comment]
Closing as this is already implemented in `2.x.x` branch
