### ISSUE TITLE
Use `Tracer` instead of `LegacyTracer`

### ISSUE THREAD

**Issue by natikgadzhi** [hummingbird-project/hummingbird#258]
Now that we have Swift 5.7 minimum, we can use the new [`Tracer`](https://swiftpackageindex.com/apple/swift-distributed-tracing/1.0.1/documentation/tracing/tracer) — not that we have to, `LegacyTracer` not being deprecated yet.

I don't think we're going to get a lot from having a concrete Span type either, in our case — if I'm reading it right, then we're setting the metadata [here in `TracingMiddleware`](https://github.com/hummingbird-project/hummingbird/blob/3c7f440cfac5ca060544f38b2083f171f9a9ee2d/Sources/Hummingbird/Middleware/TracingMiddleware.swift#L53).

Could be a good first issue for someone just playing around with Hummingbird and tracing?

**Comment by adam-fowler** [comment]
Yeah I noticed we could update to using `Tracer` now. I hadn't got around to doing anything about it. Thank you for the issue. I'm happy to accept PRs as well to resolve this.

**Comment by natikgadzhi** [comment]
I’m just learning the whole tracing layer of things, but I would love to work on this! 

Expect a PR in the next couple of days. Thank you for being open to it ❤️
