### ISSUE TITLE
Separate HBRouter and other 'core' logic into a separate package or at least module

### ISSUE THREAD

**Issue by Joannis** [hummingbird-project/hummingbird#306]
This can enable users to adopt Lambdas with the OpenAPI generator without downloading and building the large of set of dependencies that supporting HTTP, WebSocket etc brings.

**Comment by adam-fowler** [comment]
I think I'm going to close this. The problem with implementing this is both HummingbirdCore and a separate router module would use the same type `Request` but we wouldn't want either of them to be dependent on the other.
