### ISSUE TITLE
Specify `.editResponse` router method option in middleware

### ISSUE THREAD

**Issue by BastianKusserow** [hummingbird-project/hummingbird#314]
Hey there.
I am just trying out to route some of my requests trough a middleware and I am a little bit stuck as some routes the middleware intercepts would need to specify the `.editReponse` router option. Is there a possibility to do that right now?

**Comment by adam-fowler** [comment]
That should already be possible. Are you not able to provide the `.editResponse` option for the routes where you want to edit the response?

**Comment by BastianKusserow** [comment]
Sadly not if I do not know the routes path in advance and want to route depending on other criterias..

**Comment by adam-fowler** [comment]
`.editResponse` is used to edit response headers or status when you are not returning a `HBResponse` type from a route. You shouldn't need it if you are editing the response in a middleware. 

I'm not totally sure what you are trying to do. If you could post some code that would help.

**Comment by BastianKusserow** [comment]
Actually I try to do something similar to pointfree [vapor routing](https://github.com/pointfreeco/vapor-routing). This requires that every route will be processed by the middleware, which then does the routing. However, the routes are not "registered" via the default router of vapor/hummingbird, so its not possible to edit the response if required.

**Comment by adam-fowler** [comment]
Are you wanting to implement your own router using a middleware?

**Comment by BastianKusserow** [comment]
Basically, yes.

**Comment by adam-fowler** [comment]
Does your middleware shortcut the responder chain ie generate its own response and not call `next.respond` method.

**Comment by BastianKusserow** [comment]
Yes. It basically looks like this (some parts left out for brevity):
```swift
struct RouterMiddleware<Router: Parser>: HBAsyncMiddleware where Router.Input == URLRequestData {
  let router: Router
  let respond: (HBRequest, Router.Output) async throws -> any HBResponseGenerator

  func apply(to request: Hummingbird.HBRequest, next: Hummingbird.HBResponder) async throws -> Hummingbird.HBResponse {
    let requestData = URLRequestData(request: request)
    let route = self.router.parse(requestData)
    return try await self.respond(request, route).response(from: request)
  }
}
```

**Comment by adam-fowler** [comment]
`HBRouterMethods` have two helper functions `constructResponder` which create a `HBCallbackResponder` which supports streaming, response editing and response generators. Unfortunately they are currently internal to Hummingbird. I can make them public , I'll also make them `static` so you don't need an instance of `HBRouterMethods`

Do you think that would help?

**Comment by BastianKusserow** [comment]
Cannot say it for sure but that indeed sounds like it would work. Would be great if you could make them public as you said!
May I ask why this has to be specified in the first place? Is this for performance/security reasons?

**Comment by adam-fowler** [comment]
> Cannot say it for sure but that indeed sounds like it would work. Would be great if you could make them public as you said! May I ask why this has to be specified in the first place? Is this for performance/security reasons?

It was mainly an optimisation, most routes don't need the response editing capabilities. For v2 of Hummingbird I intend to get rid of this way to edit response status and header. It is hard to make it thread safe. Instead people will return a type which includes the response generator plus any edits.

**Comment by BastianKusserow** [comment]
I see, thanks for the quick reply! Looking forward to hummingbird v2

**Comment by adam-fowler** [comment]
@BastianKusserow v1.11.0 has been released with a public `HBRouterMethods.buildResponder`

**Comment by adam-fowler** [comment]
I'm going to close this as I think I have provided enough for you to implement what you need

**Comment by BastianKusserow** [comment]
Awesome, thanks a lot for the help. Just tried it out and it works like a charme!
