### ISSUE TITLE
Can `hb_id` always be unique?

### ISSUE THREAD

**Issue by sidepelican** [hummingbird-project/hummingbird#325]
Currently, `hb_id` is an integer sequence value in each process. 
I don't fully understand why current `hb_id`' works like this, but for logging I would prefer it to be unique across all processes.

This creates extra work when I query logs associated with specific requests.  
This is because logs are taken from each application server and put together (like in CloudWatch).

Vapor uses `UUID`, but Hummingbird is not.
Maybe this is because it doesn't depend on `Foundation`.
I think making a random string that's as long with `UUID`, with something like `SystemRandomNumberGenerator`, might be good.

**Comment by adam-fowler** [comment]
`hb_id` is generated from an incrementing 64 bit atomic. You would need to have 9223372036854775807 request to your server before the id generated a duplicate.

**Comment by adam-fowler** [comment]
Or are you concerned about ids across multiple processes?

**Comment by sidepelican** [comment]
Yes, I'm assuming to run application in environments like ECS or Cloud Run.

**Comment by adam-fowler** [comment]
Just using a single 64 bit value random number will increase the likely hold of clashes. I might break this into two 64 bit values. A randomly generated number per server and the incrementing value.

**Comment by sidepelican** [comment]
UUIDv4 is 122 bit.
The proposed value is 128 bit but the half bits have bias.

I would prefer to have a completely random 128-bit value,
but it is possible that sequential values would have better performance than generating random numbers.

I think both are effective.

**Comment by adam-fowler** [comment]
#326

**Comment by sidepelican** [comment]
#326 seems to be merged. thanks!
