### ISSUE TITLE
2.x.x - Bikeshedding

### ISSUE THREAD

**Issue by adam-fowler** [hummingbird-project/hummingbird#343]
Here are a list of symbol names, I'm not overly happy with but couldn't think of a better one at the time...

- [ ] `HBApplicationProtocol.processesRunBeforeServerStart`: An array of closures we run before starting the HBServer service. 
- [ ] `HTTPChannelHandler`: Protocol for child channel that can handle HTTP1.1 packets.

**Comment by Diggory** [comment]
how about `prestartProcesses` or `prestartActions`?

**Comment by adam-fowler** [comment]
> how about `prestartProcesses` or `prestartActions`?

It has to be clear these are processes that will be run before we start the server.

**Comment by Joannis** [comment]
Personally I think we're fine with these names
