### ISSUE TITLE
Allow disabling `hb_id`

### ISSUE THREAD

**Issue by slashmo** [hummingbird-project/hummingbird#377]
When using Distributed Tracing with a metadata provider, Hummingbird logs get span and trace ID metadata values automatically. This makes the `hb_id` metadata value a bit superfluous and it adds unnecessary bloat to the log statements. Therefore, it would be great if one could disable it.

**Comment by adam-fowler** [comment]
hb_id allows you to associate a trace entry with entries in your log.

**Comment by slashmo** [comment]
> hb_id allows you to associate a trace entry with entries in your log.

Isn't that what the metadata provider provided trace/span IDs already do?

**Comment by thoven87** [comment]
> hb_id allows you to associate a trace entry with entries in your log.

is hb_id used internally to attach span_id/trace_id to the logger? I just started playing with Hummingbird along with swift-otel. I noticed each log has span_id, trace_id and hb_id, since swift-otel does support log export with OTEL yet; I will try running Grafana agent to see if I can correlate logs with traces.

**Comment by slashmo** [comment]
`span_id` and `trace_id` are attached via the logging metadata handler from swift-otel. `hb_id` is not related to that. Log correlation works well with various observability tools.

**Comment by thoven87** [comment]
> `span_id` and `trace_id` are attached via the logging metadata handler from swift-otel. `hb_id` is not related to that. Log correlation works well with various observability tools.

I think I understand what `hb_id` is now. Please correct me if I am wrong @adam-fowler `hb_id` can be interpreted as `request_id` (an idempotency key) which can used to identify retries, it can be used to guaranteed at least once delivery e.t.c. Moreover, `hb_id` can be injected into any subsequent calls to other services to follow a request journey across external services as well.

**Comment by adam-fowler** [comment]
Sorry took so long to reply. 

`hb_id` is used to identify log entries that belong to a single request regardless of whether you are using Tracing or not. If the logger is passed down to services the request uses then those services log entries will include it as well. 

If you really want to remove the `hb_id` metadata from your log entries you could write a middleware that removes it from the logger.

Originally I wanted to use metadata providers in Hummingbird but I haven't found a method where I can use them without trampling over metadata from other system eg swift-otel 

@slashmo Out of interest when are the trace-id and span-id set?

**Comment by slashmo** [comment]
> Sorry took so long to reply.
> @adam-fowler

Likewise 😅

> `hb_id` is used to identify log entries that belong to a single request regardless of whether you are using Tracing or not. If the logger is passed down to services the request uses then those services log entries will include it as well.

Makes sense! My point is that _if_ you're using tracing with a metadata provider there's as far as I can tell no advantage to _also_ have `hb_id` in the logs.

> Originally I wanted to use metadata providers in Hummingbird but I haven't found a method where I can use them without trampling over metadata from other system eg swift-otel

Unless your metadata keys clash with those from other metadata providers, there shouldn't be an issue. For a key like `hb_id` I don't see this being a common case. End-users can use a multiplex metadata provider to set up both Hummingbird's and `swift-otel`'s at the same time: https://github.com/apple/swift-log/blob/d16e216341cd13c4f72bf53164dd39acbf14ebbd/Sources/Logging/MetadataProvider.swift#L87
Do you still happen to have a WIP of this? I'd be happy to give it a look and see if it would be feasible.

> Out of interest when are the trace-id and span-id set?

They are set by the metadata provider, looking up the task-local `ServiceContext`: https://github.com/slashmo/swift-otel/blob/1c32237fbd0947f19b59df212d3060147c769e59/Sources/OTel/Logging/MetadataProvider%2BOTel.swift#L35

**Comment by Joannis** [comment]
@slashmo what do you think of keeping the requestID, but moving in into `RequestContextSource`? That way we could leverage the IDs provided by AWS Lambda as well within Hummingbird

**Comment by adam-fowler** [comment]
@Joannis I'm not sure how this helps. The only reason we have `hb_id` is so all the log entries from the one request can be recognised in logs. @slashmo 's issue as I see it is he already has an id attached to the logger, and considers `hb_id` as clutter. I think he just wants an option to not add it to the logger.

**Comment by adam-fowler** [comment]
Just realised you can disable the hb_id from the logger using a custom RequestContext
```swift
struct RemoveIDRequestContext: RequestContext {
    var coreContext: CoreRequestContextStorage
    init(source: Source) {
        self.coreContext = .init(source: source)
        self.logger[metadataKey: "hb_id"] = nil
    }
}
```

**Comment by slashmo** [comment]
> ... he already has an id attached to the logger, and considers hb_id as clutter. I think he just wants an option to not add it to the logger.
> @adam-fowler

Yes, although I don't have an ID attached to the logger directly. It's implicitly added via the OTel logging metadata provider. Since the tracing middleware already starts a span, this basically means trace and span IDs are included in all logs further down the task-tree.

> Just realised you can disable the hb_id from the logger using a custom RequestContext
> @adam-fowler 

Nice, haven't thought about this. To me, this is a good enough solution 👍 Feel free to close the issue if you agree.
