### ISSUE TITLE
Consideration: Use `AsyncSequence<ByteBuffer>` to represent a request body

### ISSUE THREAD

**Issue by Joannis** [hummingbird-project/hummingbird#381]
In Swift 6 we can remove `AnyAsyncSequence`. https://github.com/apple/swift-evolution/blob/main/proposals/0421-generalize-async-sequence.md

**Comment by adam-fowler** [comment]
I think I'll always have a wrapper type to hide the implementation but moving to `any AsyncSequence<ByteBuffer>` when it becomes available would be good.
