### ISSUE TITLE
1.12.0 Does not contain all commits from branch 1.1.x

### ISSUE THREAD

**Issue by ronaldmannak** [hummingbird-project/hummingbird#410]
Version 1.12.0 does not contain the last commits and fixes on the 1.1.x branch. Would it be possible to release one final version 1.x before 2.0? That way 1.x.x developers adding the package with a `from: 1.12.0` version don't run into already fixed issues.

**Comment by adam-fowler** [comment]
Good point. I have one other fix that should probably be merged, and I'll do another release

**Comment by adam-fowler** [comment]
Done
