### ISSUE TITLE
Streaming issues

### ISSUE THREAD

**Issue by tib** [hummingbird-project/hummingbird#459]
Hello,

I'd like to report a potential but very strange streaming issue or bug that results in excessively high memory usage, 0% CPU usage, or even corrupted bytes in the streamed data. It seems to be related to threading, or possibly something else, but running the following test consistently produces unusual results.

Given the [upload example code](https://github.com/hummingbird-project/hummingbird-examples/tree/main/upload), I changed the test case with the following code (trying to upload 10x50MB data in parallel, it even happens with 5MB data, also experimented with 500MB):

```swift
@testable import App
import Hummingbird
import HummingbirdTesting
import XCTest

final class AppTests: XCTestCase {

    struct TestArguments: AppArguments {
        var hostname: String { "127.0.0.1" }
        var port: Int { 0 }
    }

    func testUploadDownload() async throws {
        let app = buildApplication(args: TestArguments())

        await withThrowingTaskGroup(of: Void.self) { group in
            // 10 threads
            for i in 0...10 {
                group.addTask {
                    // 50 mb using the live test config
                    try await self.runUploadTest(app, .live, i, 50)
                }
            }
        }
    }
    
    func runUploadTest(
        _ app: any ApplicationProtocol,
        _ setup: TestingSetup,
        _ i: Int,
        _ size: Int = 1
    ) async throws {
        try await app.test(setup) { client in
            var bytes = [UInt8](repeating: 0, count: 1024 * 1024 * size)
            for j in 0...100 {
                bytes[j] = UInt8(j + i)
            }

            let buffer = ByteBuffer(bytes: bytes)
            let testFileName = "Hello-\(i).txt"
            let testUpload = UploadModel(filename: testFileName)
            let uploadURL = try testUpload.destinationURL(allowsOverwrite: true)
            defer {
                try? FileManager.default.removeItem(at: uploadURL)
            }
            print("---upload---")
            try await client.execute(
                uri: "/files",
                method: .post,
                headers: [.fileName: testFileName],
                body: buffer
            ) { response in
                XCTAssertEqual(response.status, .ok)
            }
            
            print("--download--")
            try await client.execute(uri: "/files/\(testFileName)", method: .get) { response in
                let dlBytes = response.body.getBytes(at: 0, length: response.body.readableBytes)

                let isOk = dlBytes == bytes
                XCTAssertTrue(isOk, "Downloaded bytes should match uploaded bytes")
            }
        }
    }
}
```

Am I doing something wrong, or is this actually a streaming bug in the framework / test suite? Thank you for the help.

FYI: I'm using Swift 5.10 + HB2 beta 5, the issue is still present.

Best,
Tib

**Comment by adam-fowler** [comment]
Ok there is a bug in `NIOAsyncChannel` where downloaded data does not always get flushed when a connection is closed. I need to chase this up with the NIO team. 

When you say high memory usage is this still high when you take into account the buffers you have allocated in the test framework?

**Comment by tib** [comment]
Yes, I was using 10 x 50 MB data, I expected a maximum of ~1GB memory usage, but it went up to 5.86GB after a while, so that's quite unexpectedly high. See the attached screenshot:

![Screenshot 2024-05-22 at 09 37 33](https://github.com/hummingbird-project/hummingbird/assets/330813/015053c1-ae06-40e8-be3e-4a6cf5d6b68f)

**Comment by adam-fowler** [comment]
Hi @tib I cannot replicate your results. The memory goes up to a max of about 1.2GB and everything is returned as expected.
As an experiment I moved the client code out to a separate executable and the server memory usage never went above 64MB.

Interestingly your test code sets up 10 servers running in parallel instead of what I assume you intended which is have 1 server process 10 requests. Each time you call `test(.live)` you are starting a new server.

**Comment by adam-fowler** [comment]
> Ok there is a bug in `NIOAsyncChannel` where downloaded data does not always get flushed when a connection is closed. I need to chase this up with the NIO team.

This is probably not relevant to this bug here. We are reading all the data from the response before closing the connection.

**Comment by adam-fowler** [comment]
@tib did using one test server fix this?

**Comment by tib** [comment]
Seems like this is fine.
