### ISSUE TITLE
Missing CORS headers when request fails

### ISSUE THREAD

**Issue by corysullivan** [hummingbird-project/hummingbird#460]
When using the CORSMiddleware, the `accessControlAllowOrigin` header is not added to a response that fails. Consequently, the browser blocks the response, preventing me from accessing the status code or error details.

I would expect the response to include the `accessControlAllowOrigin` header, enabling the front end to retrieve the status code and other error details.

**Comment by adam-fowler** [comment]
#461

**Comment by adam-fowler** [comment]
in beta 6 release
