### ISSUE TITLE
Http1.1 pipelining in parallel

### ISSUE THREAD

**Issue by Bersaelor** [hummingbird-project/hummingbird#467]
Hey there, big Server-Side-Swift fan,

so I was really happy to find that hummingbird using HTTP 1.1 allows for multiple connections via the same connection, i.e. I can

```bash
(echo -en "GET /test HTTP/1.1\nHost: host.com\nConnection: keep-alive\n\nGET /test/special HTTP/1.1\nHost: host.com\n\n"; sleep 10) | telnet host.com 80
```
send two `GET` requests over the same connection, and both succeed.

But it seems that they don't execute asynchronously, i.e. if I artificially make each request only respond after 1s, it is:
`1s wait`
`response1`
`1s wait`
`response2`

not

`1s wait`
`response1`
`response2`

Is there anyway I can unlock 1.1 pipelining concurrency with a simple setting?

I started with this [proxy example](https://github.com/hummingbird-project/hummingbird-examples/blob/main/proxy-server/Sources/App/Middleware/ProxyServerMiddleware.swift) to try to build a concurrent proxy.
None of the python/express.js/nginx proxies do pipelining anymore, so this would be a godsend (and easy on the hardware too, given that it's all swift!)

**Comment by adam-fowler** [comment]
Updating from conversation on [Vapor discord](https://discord.com/channels/431917998102675485/1225769138291605574). Come join us on the [HB discord](https://discord.gg/7ME3nZ7mP2) if you want to discuss further.

Hummingbird 2 does not support concurrent execution of pipelined HTTP1.1 requests. It is considered dangerous and responses can be returned out of order. But Hummingbird 1 does have a switch to enable this: `HBApplication.Configuration. enableHttpPipelining`. This does not provide any protection against out of order responses. To guarantee this you would need to fork Hummingbird 1.
- Add a fifo queue of `EventLoopPromise<HBResponse>` to `HBHTTPServerHandler`
- With each request add a new entry and once that request is complete fulfill the related promise
- Add a separate thread (running on same EventLoop) that pops the first entry off the queue waits for that to complete, writes the response, and repeats. 

You need to be able to trigger the separate thread to only run when a response is available, so it might be better to prime your queue with a single promise and when you receive a request add the new promise but complete the previous promise once you have the response from the request.

**Comment by adam-fowler** [comment]
Closing this as it won't be something we are implementing directly in Hummingbird
