### ISSUE TITLE
2.x: Slow troughput for `FileIO.readFile()`

### ISSUE THREAD

**Issue by andreasley** [hummingbird-project/hummingbird#470]
Using [`FileIO.readFile()`](https://github.com/hummingbird-project/hummingbird/blob/ea60c9b2d66ddb27e2aa06982a1c5477f9a50b83/Sources/Hummingbird/Files/FileIO.swift#L106) seems to be much slower than `FileIO.writeFile()` and CPU usage is very high. This has the effect that, on my machine, downloading large files is limited to ~50MB/s while uploading is possible at 1GB/s or more.

I've noticed the following:
- A larger chunk size increases the throughput considerably
- The relevant `chunkSize` is defined in `readFile()` as `8 * 1024` (so 8 kB)
- The `chunkSize` defined in the struct `FileIO` is not used at all (but would read from `NonBlockingFileIO.defaultChunkSize`, which is much larger at 128 kB)

Suggestions:
- Make `chunkSize` an optional parameter for `loadFile()` and `readFile()`, defaulting to `NonBlockingFileIO.defaultChunkSize`
- Remove `chunkSize` in `FileIO`

I can make a pull request with these changes if you find them reasonable.

PS: Thanks for this great library!

**Comment by adam-fowler** [comment]
ok go ahead, thanks for the offer of the PR
