### ISSUE TITLE
HTTPResponseError is now a ResponseGenerator

### ISSUE THREAD

**Issue by sidepelican** [hummingbird-project/hummingbird#501]
After this PR, https://github.com/hummingbird-project/hummingbird/pull/484

This PR has made `HTTPResponseError` a confusing entity.
Although `status` and `headers` are included as requirements, but there are no meaningful usages.
It is no different from `ResponseGenerator`.

To avoid confusion, we should either remove it, or provide a default conformance to `ResponseGenerator`.

**Comment by adam-fowler** [comment]
`status` and `headers` are used in both the tracing and metrics middleware, so we can't just conform to ResponseGenerator as we need this additional information.

**Comment by sidepelican** [comment]
Sorry, I missed the usage in TracingMiddleware. My thoughts are written here: https://github.com/hummingbird-project/hummingbird/pull/502#issuecomment-2207866751
