### ISSUE TITLE
FileMiddleware in RouterGroup

### ISSUE THREAD

**Issue by sliemeobn** [hummingbird-project/hummingbird#509]
Currently there is not good way to have a FileMiddleware be aware of a base path.

When placing it in a group, the files are still looked up with the group's path in place.

Eg:
```swift
router.group("my-path")
   .add(middleware: FileMiddleware("my-folder"))
```

When requesting `/my-path/someFile` it will be looked up (and not found) under `my-folder/my-path/someFile`.

Additionally, `FileMiddleware` (as middlewares in general) are not actually called if no route matches in a group. For most middlewares this is expected, but since file middleware is expected to match "everything else", this can be counter-intuitive.

**Comment by sliemeobn** [comment]
just as potential inspiration, I added this hacky work-around for me for now:

```swift
// made an extension method on router group
router.group("my-path").serveFiles(fromBundlePath: "/Public")

// this looks like this
extension RouterGroup {
    @discardableResult
    func serveFiles(fromBundlePath path: String) -> Self {
        let group = self.group("*")
        let middleware = FileMiddleware<Context, LocalFileSystem>(bundlePath: path)
        group.get(use: middleware.serve(request:context:))
        group.head(use: middleware.serve(request:context:))
        return self
    }
}

// with this abomination to get to the good stuff of the file middleware
extension FileMiddleware where Provider == LocalFileSystem {
    @Sendable func serve(request: Request, context: Context) async throws -> Response {
        var head = request.head
        let basePath = context.endpointPath?.replacingOccurrences(of: "*", with: "") ?? ""

        head.path = request.uri.path.replacingOccurrences(of: basePath, with: "")

        let request = Request(head: head, body: request.body)

        return try await self.handle(request, context: context) { _, _ -> Response in
            throw HTTPError(.notFound)
        }
    }
}
```

One thing that would help here: if all the magic of etag-checking and the likes could be on a public extension on the FileSystem. This way one could hook it up in actually matched router handlers.

**Comment by adam-fowler** [comment]
#510
