### ISSUE TITLE
How to specify a bonjour endpoint to listen on?

### ISSUE THREAD

**Issue by Dev1an** [hummingbird-project/hummingbird#522]
Swift NIO-ts uses this nice way to bind a server to a NWEndpoint. So you can let your webserver listen on a bonjour service instead of an IP address. See
- https://github.com/apple/swift-nio-transport-services/blob/38ac8221dd20674682148d6451367f89c2652980/Sources/NIOTransportServices/NIOTSListenerBootstrap.swift#L287-L295
- https://github.com/apple/swift-nio-transport-services/blob/main/Sources/NIOTransportServices/NIOTSNetworkEvents.swift#L71-L81

In humming bird I only find configurations to listen on a specific hostName or ip address. Is it possible to specify to listen on NWEndpoints?

**Comment by adam-fowler** [comment]
It's on my list of things to do. I need to verify the new NIOAsyncChannel bind functions support NWEndpoint

**Comment by Joannis** [comment]
NIOAsyncChannel can wrap an existing Network Services `Channel`

**Comment by adam-fowler** [comment]
#525

**Comment by adam-fowler** [comment]
Merged will be in the next release
