### ISSUE TITLE
environ not concurrecy-safe in Swift 6 CrossCompilation, aarch64 musl

### ISSUE THREAD

**Issue by ilgrandeanonimo** [hummingbird-project/hummingbird#536]
I encurred into the concurrency-unsafe error during the compilation of my package

**Command:** `swift build --product ModeratorWebAPI -c release --swift-sdk aarch64-swift-linux-musl --toolchain /Library/Developer/Toolchains/swift-6.0-DEVELOPMENT-SNAPSHOT-2024-08-22-a.xctoolchain`

**Error:**
```sh
/Users/paolo/Developer/Swift/Moderator/.build/checkouts/hummingbird/Sources/Hummingbird/Environment.swift:111:26: error: reference to var 'environ' is not concurrency-safe because it involves shared mutable state
109 |         let equalSign = Character("=")
110 |         #if canImport(Musl)
111 |         guard let envp = environ else { return [:] }
    |                          `- error: reference to var 'environ' is not concurrency-safe because it involves shared mutable state
112 |         #else
113 |         let envp = environ

posix_unistd.environ:1:12: note: var declared here
1 | public var environ: UnsafeMutablePointer<UnsafeMutablePointer<CChar>?>!
  |
```

**Comment by adam-fowler** [comment]
Yep I've seen that. This needs to be reported in the swift repo. I just haven't got around to this.
You'll also come across this issue [#515](https://github.com/hummingbird-project/hummingbird/issues/515#issuecomment-2266674313) where it crashes. There is a fix on swift-async-algorithms it just hasn't been released yet
