### ISSUE TITLE
Review of all the metrics names and logger metadata names

### ISSUE THREAD

**Issue by adam-fowler** [hummingbird-project/hummingbird#539]
Below is a list of logger metadata names, plus associated log output and where the call is made
Logger metadata:
- `error`: "Unrecognised error" Application.swift. 
- `file`: "PUT" FileIO.swift
- `hb_uri`, `hb_method`, `hb_headers`: "Request" LogRequestMiddleware.swift
- `error`: "Failed to get job from queue" PostgresJobsQueue.swift
- `error`: "WebSocket handler error" WebSocketChannel.swift/WebSocketRouter.swift
- `hb_extensions`: "Extensions required" WebSocketChannel.swift
- `opcode`: "Received reserved opcode" WebSocketInboundStream.swift
- `JobID`, `JobName`, `JobTime`: JobQueue.swift

Metrics names:
- `hb_requests`: dimensions: `hb_uri`, `hb_method`
- `hb_errors`: dimensions: `hb_uri`, `hb_method`
- `hb_request_duration`: dimensions: `hb_uri`, `hb_method`
- `swift_jobs`: dimensions: `name`, `status`
- `swift_jobs_meter`: dimensions: `name`, `status`

**Comment by adam-fowler** [comment]
Initial thoughts:
logger metadata: should we prefix all the HB metadata with `hb_` and change the jobs metadata back to snake case. 
metrics: do we need the `swift_` prefix? I'm not sure if dimensions need a prefix at all

**Comment by thoven87** [comment]
Since we're trying to future proof the metric tags and so forth. Should we convert to the Open Telemetry convention?

In Open Telemetry, the dot notion is used instead of the underscore. Both Prometheus and Loki will have both options available.

**Comment by adam-fowler** [comment]
I'm happy to go with dot notation `hb.uri`, `job.name`.

**Comment by thoven87** [comment]
> I'm happy to go with dot notation `hb.uri`, `job.name`.

Probably not `job.name` I think this one would conflict with OpenTelemetry collectors. @Joannis Do you have any preferences?

**Comment by adam-fowler** [comment]
> Probably not job.name I think this one would conflict with OpenTelemetry collectors.

I don't see anything in the OTel spec which uses `job` but we could use `jobs` or `hb.job` instead I guess.

**Comment by thoven87** [comment]
The OpenTelemetry semantic conventions for HTTP metrics can found [here](https://opentelemetry.io/docs/specs/semconv/http/http-metrics/)

Plus more

[HTTP spans](https://opentelemetry.io/docs/specs/semconv/http/http-spans/)

[Exceptions for Logs](https://opentelemetry.io/docs/specs/semconv/exceptions/exceptions-logs/)

[Exception for spans](https://opentelemetry.io/docs/specs/semconv/exceptions/exceptions-spans/)

[Prometheus Compatibility](https://opentelemetry.io/docs/specs/otel/compatibility/prometheus_and_openmetrics/)

[It looks like UTF-8 support for label and metric names](https://github.com/prometheus/prometheus/issues/13095) in Prometheus will not land 'till version 3.0.

**Comment by adam-fowler** [comment]
So I've followed the conventions for HTTP metrics
There is very little detail when it comes to log attributes. I've used an `hb` prefix everywhere to ensure we aren't adding to namespaces we don't own.
