### ISSUE TITLE
Error referencing environ with Linux SDK

### ISSUE THREAD

**Issue by seanmrich** [hummingbird-project/hummingbird#564]
I created a test project using the template and tried cross compiling for Linux using the latest release versions of swift and the static SDK. I get an error that environ is not concurrency-safe in Sources/Hummingbird/Environment line 111.

% git clone https://github.com/hummingbird-project/template
% ./template/configure.sh Hummer
% cd Hummer
% swift build --swift-sdk x86_64-swift-linux-musl
/.../Hummer/.build/checkouts/hummingbird/Sources/Hummingbird/Environment.swift:111:26: error: reference to var 'environ' is not concurrency-safe because it involves shared mutable state
I tried changing the package's tools version to swift 5.9, but got the same result. The environ variable is defined in Darwin so I'm not sure how to proceed here. It compiles fun under macOS but not Linux.

swift toolchain org.swift.6010202409231a (version 6.0.1)
linux sdk swift-6.0.1-RELEASE_static-linux-0.0.1
hummingbird 2.0.1

First posted as a [discussion](https://github.com/hummingbird-project/hummingbird/discussions/563)

**Comment by adam-fowler** [comment]
Ah I meant create an issue in swiftlang/swift. The treatment of environ is inconsistent between glibc and musl.

**Comment by Joannis** [comment]
I haven't had this issue interestingly enough. Even with the same SDK and toolchain

**Comment by adam-fowler** [comment]
Last time I tried with swift 6 it couldn't find the internal version of collections used by foundation. Maybe they fixed that with 6.0.1

**Comment by seanmrich** [comment]
The newest release fixes the issue with missing `_FoundationCollections`. What I found was a different issue. Would love to know if I'm just doing it wrong, but I'm just building the template with no changes.
