### ISSUE TITLE
Use ProcessInfo.processInfo.environment instead of environ.

### ISSUE THREAD

**Issue by adam-fowler** [hummingbird-project/hummingbird#571]
We are using Foundation in Hummingbird now so this shouldn't be an issue. It'll also allow us to get around the static sdk issues with `environ`.

**Comment by Joannis** [comment]
I don't know why, but I've found Foundation ProcessInfo's environment to be not-thread safe at a customer. Maybe that's no longer the case with swift-foundation though.

**Comment by adam-fowler** [comment]
I had a look through the code and it looks thread safe. It'll be better than using environ where in glibc/darwin it claims to be Sendable but there's a good chance it isn't. It is a char**
