### ISSUE TITLE
The static method 'shutdownDataCaches' should be 'shutDownDateCaches'

### ISSUE THREAD

**Issue by brucemontegani** [hummingbird-project/hummingbird#91]
The method 'shutdownDataCaches' on class 'HBDateCache' is misspelled. It should be 'shutdownDateCaches'

<img width="1087" alt="hummingbird-misspelling" src="https://user-images.githubusercontent.com/9996864/123023531-62b76380-d38c-11eb-9af8-2bfe53b8cb21.png">

**Comment by adam-fowler** [comment]
Good spot, I'm quite good at making that typo

**Comment by adam-fowler** [comment]
e880b0e2958fe12c5433bc42b4b9e126d44e702e
